# Generated by Django 2.2.4 on 2019-10-16 04:47

from django.db import migrations


def create_default_roles(apps, schema_editor):
    roles = [("collaborator", "Collaborator for your companies"), ("Client", "Client for your companies")]
    user_role = apps.get_model('users', 'UserRole')

    for role in roles:
        user_role.objects.create(name=role[0], description=role[1])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userrole_usertouserrole'),
    ]

    operations = [
        migrations.RunPython(create_default_roles)
    ]
