# Generated by Django 2.2.4 on 2019-10-20 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191015_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertouserrole',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
