# Generated by Django 2.2.4 on 2019-10-23 16:49

from django.db import migrations


def create_default_groups(apps, schema_editor):
    groups = [('owner', 'Owner for one or many companies'), ('collaborator', 'Collaborator for many owners'),
              ('client', 'Client for many owners')]
    auth_group = apps.get_model('auth', 'Group')

    for group in groups:
        auth_group.objects.create(name=group[0])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usertouserrole_created_at'),
    ]

    operations = [
        migrations.RunPython(create_default_groups)
    ]
