# Generated by Django 2.2.4 on 2019-10-25 05:55

from django.db import migrations


def set_permissions_to_collaborators(apps, scheme_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model('auth', 'Group')
    users_content_type = content_type_model.objects.get(app_label='users', model='user')
    permissions = permission_model.objects.filter(content_type=users_content_type,
                                                  codename__in=['view_owners'])
    group = group_model.objects.get(name='collaborator')

    for permission in permissions:
        group_permission = group.permissions.add(permission)
        print(group_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20191024_2354'),
    ]

    operations = [
        migrations.RunPython(set_permissions_to_collaborators)
    ]
