# Generated by Django 2.2.4 on 2019-11-05 19:54

from django.db import migrations


def categories_permissions(apps, scheme_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model('auth', 'Group')
    users_content_type = content_type_model.objects.get(app_label='categories', model='category')

    permissions = permission_model.objects.filter(content_type=users_content_type,
                                                  codename__in=['view_category'])
    groups = group_model.objects.filter(name__in=['collaborator', 'client', 'owner'])

    for group in groups:
        for permission in permissions:
            group_permission = group.permissions.add(permission)
            print(group_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20191024_2355'),
    ]

    operations = [
        migrations.RunPython(categories_permissions)
    ]
