# Generated by Django 2.2.4 on 2019-11-05 21:08

from django.db import migrations


def parameters_permissions(apps, scheme_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model('auth', 'Group')
    users_content_type = content_type_model.objects.get(app_label='parameters_response_types', model='responsetype')

    permissions = permission_model.objects.filter(content_type=users_content_type,
                                                  codename__in=['view_responsetype'])

    groups = group_model.objects.filter(name__in=['collaborator', 'client', 'owner'])

    for group in groups:
        for permission in permissions:
            group_permission = group.permissions.add(permission)
            print(group_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191105_1354'),
        ('parameters_response_types', '0001_initial')
    ]

    operations = [
        migrations.RunPython(parameters_permissions)
    ]
