dist: xenial

language: python

python:
  - 3.6.4

services: mysql

install:
  - pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py test

after_success:
  - python -m codecov

