# Generated by Django 2.2.4 on 2019-09-05 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_response_types', '0003_responsetypegroup_response_types'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='response_type_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam_response_types.ResponseTypeGroup'),
        ),
        migrations.AddField(
            model_name='exam',
            name='type',
            field=models.CharField(choices=[('static', 'static'), ('dynamic', 'dynamic')], max_length=20, null=True),
        ),
    ]
