# Generated by Django 2.2.4 on 2019-09-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam_response_types', '0005_auto_20190906_0656'),
        ('exams', '0003_exam_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicExamAssignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField(default=0)),
                ('max', models.FloatField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_response_types.Unit')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='dynamic_exam_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.DynamicExamAssignation'),
        ),
    ]
