# Generated by Django 2.2.4 on 2019-09-19 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20190914_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='dynamic_exam_assignation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.DynamicExamAssignation'),
        ),
    ]
