# Generated by Django 2.2.4 on 2019-09-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20190925_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='unit',
        ),
    ]
