# Generated by Django 2.2.4 on 2019-08-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_response_types', '0002_auto_20190830_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsetypegroup',
            name='response_types',
            field=models.ManyToManyField(through='exam_response_types.ResponseTypeAssignation', to='exam_response_types.ResponseType'),
        ),
    ]
