# Generated by Django 2.2.4 on 2019-09-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_response_types', '0004_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
