# Generated by Django 2.2.4 on 2019-10-12 06:33

from django.db import migrations


def create_default_roles(apps, schema_editor):
    roles = [
        ('owner', 'Owner for the analysis'),
        ('creator', 'Creator for the analysis')
    ]
    AnalysisRole = apps.get_model('analysis', 'AnalysisRole')

    for role in roles:
        AnalysisRole.objects.create(name=role[0], description=role[1])


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles)
    ]
