# Generated by Django 2.2.4 on 2019-10-16 02:27

from django.db import migrations


def create_default_roles(apps, schema_editor):
    roles = [('administrator', 'All permissions for company'), ('collaborator', 'Restricted permissions for companies')]
    company_role = apps.get_model('companies', 'CompanyRole')
    for role in roles:
        company_role.objects.create(name=role[0], description=role[1])


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_roles)
    ]
