# Generated by Django 2.2.4 on 2019-09-19 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyexamassociation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyexamassociation',
            name='user',
        ),
    ]
