# Generated by Django 2.2.4 on 2019-10-23 21:01

from django.db import migrations


def set_permissions_to_owner(apps, scheme_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    print(content_type_model)
    permission_model = apps.get_model('auth', 'Permission')
    print(permission_model)
    group_model = apps.get_model('auth', 'Group')
    print(group_model)
    companies_content_type = content_type_model.objects.get(app_label='companies', model='company')
    print(companies_content_type)
    permissions = permission_model.objects.filter(content_type=companies_content_type,
                                                  codename__in=['view_company', 'change_company'])
    print(permissions)
    group = group_model.objects.get(name='owner')
    print(group)
    for permission in permissions:
        group_permission = group.permissions.add(permission)
        print(group_permission)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20191015_2027'),
        ('users', '0005_auto_20191023_1049')
    ]

    operations = [
        migrations.RunPython(set_permissions_to_owner)
    ]
