# Generated by Django 2.2.4 on 2019-10-23 23:45

from django.db import migrations


def set_permissions_to_collaborator(apps, scheme_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model('auth', 'Group')
    companies_content_type = content_type_model.objects.get(app_label='companies', model='company')
    permissions = permission_model.objects.filter(content_type=companies_content_type,
                                                  codename__in=['view_company', 'change_company'])
    print(permissions)
    group = group_model.objects.get(name='collaborator')
    for permission in permissions:
        group_permission = group.permissions.add(permission)


def set_permissions_to_client(apps, scheme_editor):
    content_type_model = apps.get_model('contenttypes', 'ContentType')
    permission_model = apps.get_model('auth', 'Permission')
    group_model = apps.get_model('auth', 'Group')
    companies_content_type = content_type_model.objects.get(app_label='companies', model='company')
    permissions = permission_model.objects.filter(content_type=companies_content_type,
                                                  codename__in=['view_company'])
    print(permissions)
    group = group_model.objects.get(name='client')
    for permission in permissions:
        group_permission = group.permissions.add(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20191023_1501'),
    ]

    operations = [
        migrations.RunPython(set_permissions_to_collaborator),
        migrations.RunPython(set_permissions_to_client)
    ]
