# Generated by Django 2.2.4 on 2019-09-25 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_company_companies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='companies',
            new_name='exams',
        ),
    ]
