# Generated by Django 2.2.4 on 2019-10-02 20:34

from django.db import migrations


def create_default_roles(apps, schema_editor):
    roles = ['administrator', 'collaborator', 'client']
    CompanyRole = apps.get_model('companies', 'CompanyRole')

    for role in roles:
        CompanyRole.objects.create(name=role, description=role)


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyexamassociationvalue'),
    ]

    operations = [
        migrations.RunPython(create_default_roles)
    ]
