# Generated by Django 2.2.4 on 2019-10-02 21:05

from django.db import migrations


def create_patient_role(apps, schema_editor):
    CompanyRole = apps.get_model('companies', 'CompanyRole')
    CompanyRole.objects.create(name='patient', description='patient')


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_auto_20191002_1434'),
    ]

    operations = [
        migrations.RunPython(create_patient_role)
    ]
